version: "3.7"
services:
  web:
    build: .
    ports:
      - "80:5000"
    links:
      - redis
    networks:
      - mynet
  redis:
    image: redis
    expose:
      - "6379"
    networks:
      - mynet
networks:
  mynet: