version: "3.8"
services:
  db:
    image: docker.io/library/postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nikhil
      POSTGRES_PASSWORD: abc123
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: docker.io/dpage/pgadmin4
    depends_on:
      - db
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: nikhil.pagote@gmail.com
      PGADMIN_DEFAULT_PASSWORD: abc123
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: